server:
  port: 8084

spring:
  application:
    name: job-service

spring.datasource:
  url: jdbc:mysql://localhost:3306/zidiodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: root
  password: YourNewPassword123!
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
