server:
  port: 8088

spring:
  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: srivilliamsai@gmial.com
    password: vguq lxuh vrjx ddbx 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
